/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminTable: typeof import('./src/components/Content/Table/AdminTable.vue')['default']
    Back: typeof import('./src/components/Content/Back.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Echarts: typeof import('./src/components/Content/Echarts.vue')['default']
    EditDialog: typeof import('./src/components/Content/Dialog/EditDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Information: typeof import('./src/components/Content/Information.vue')['default']
    InsertAdmin: typeof import('./src/components/Content/Dialog/InsertAdmin.vue')['default']
    InsertAdminDialog: typeof import('./src/components/Content/Dialog/InsertAdminDialog.vue')['default']
    InsertDialog: typeof import('./src/components/Content/Dialog/InsertDialog.vue')['default']
    PasswordDialog: typeof import('./src/components/Content/Dialog/PasswordDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selectors: typeof import('./src/components/Content/Selectors.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Title: typeof import('./src/components/Content/Title.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    Upload: typeof import('./src/components/Content/Upload.vue')['default']
    UserTable: typeof import('./src/components/Content/Table/UserTable.vue')['default']
  }
}
